hexagons = ->
  c = document.getElementById 'canvas'
  w = c.width = window.innerWidth
  h = c.height = window.innerHeight
  sum = w + h
  ctx = c.getContext('2d')
  opts =
    side: 35
    picksParTick: 2
    baseTime: 400
    addedTime: 100
    colors: [
      'rgba(0,0,0,alp)'
      'rgba(180,30,30,alp)'
      'rgba(255,255,255,alp)'
    ]
    addedAlpha: 20
    strokeColor: 'rgb(255,255,255)'
    hueSpeed: .4
    repaintAlpha: 1
  difX = Math.sqrt(3) * opts.side / 2
  difY = opts.side * 3 / 2
  rad = Math.PI / 6
  cos = Math.cos(rad) * opts.side
  sin = Math.sin(rad) * opts.side
  hexs = []
  tick = 0

  looop = ->
    window.requestAnimationFrame looop
    tick += opts.hueSpeed
    ctx.shadowBlur = 0
    ctx.fillStyle = 'rgba(100,100,100,alp)'.replace('alp', opts.repaintAlpha)
    ctx.fillRect 0, 0, w, h
    i = 0
    while i < opts.picksParTick
      hexs[Math.random() * hexs.length | 0].pick()
      ++i
    hexs.map (hex) ->
      hex.step()
      return
    return

  Hex = (x, y) ->
    @x = x
    @y = y
    @sum = @x + @y
    @picked = false
    @time = 0
    @targetTime = 0
    @xs = [
      @x + cos
      @x
      @x - cos
      @x - cos
      @x
      @x + cos
    ]
    @ys = [
      @y - sin
      @y - (opts.side)
      @y - sin
      @y + sin
      @y + opts.side
      @y + sin
    ]
    return

  Hex::pick = ->
    @color = opts.colors[Math.random() * opts.colors.length | 0]
    @picked = true
    @time = @time or 0
    @targetTime = @targetTime or opts.baseTime + opts.addedTime * Math.random() | 0
    return

  Hex::step = ->
    prop = @time / @targetTime
    ctx.beginPath()
    ctx.moveTo @xs[0], @ys[0]
    i = 1
    while i < @xs.length
      ctx.lineTo @xs[i], @ys[i]
      ++i
    ctx.lineTo @xs[0], @ys[0]
    if @picked
      ++@time
      if @time >= @targetTime
        @time = 0
        @targetTime = 0
        @picked = false
      ctx.fillStyle = ctx.shadowColor = @color.replace('alp', Math.sin(prop * Math.PI))
      ctx.fill()
    else
      ctx.strokeStyle = ctx.shadowColor = opts.strokeColor
      ctx.stroke()
    return

  x = 0
  while x < w
    i = 0
    y = 0
    while y < h
      ++i
      hexs.push new Hex(x + difX * i % 2, y)
      y += difY
    x += difX * 2
  looop()
  window.addEventListener 'resize', ->
    `var x`
    `var i`
    `var y`
    w = c.width = window.innerWidth
    h = c.height = window.innerHeight
    sum = w + h
    hexs.length = 0
    x = 0
    while x < w
      i = 0
      y = 0
      while y < h
        ++i
        hexs.push new Hex(x + difX * i % 2, y)
        y += difY
      x += difX * 2
    return

  # ---
  # generated by js2coffee 2.2.0
