---
white1: "#ffffff"
white2: "#f1f1f1"
white3: "#F4F4F4"
grey1: "#e5e5e5"
grey2: "#f5f5f5"
grey3: "#d0d0d0"
black1: "#000000"
black2: "#282828"
black3: "#333333"

red1: "#C8212B"
cyan1: "#5FA793"
yellow1: "#F6BB45"
orange1: "#F68F62"
skin1: "#F3DDA3"
green1: "#5ba541"
green2: "#88d96d"
green3: "#77d358"

google_blue: "#4285f4"
google_green: "#34a853"
google_yellow: "#fbbc05"
google_red: "#ea4335"

github_blue: "#0D2636"
facebook_blue: "#4867AA"
instagram_or: "#FF7804"
twitter_blue: "#00ACED"

