---

h1: 
  font-family: Roboto
  font-size: 34px
  font-weight: '300'
h1b: 
  font-family: Roboto
  font-size: 34px
  font-weight: '700'
h2: 
  font-family: Roboto
  font-size: 24px
  font-weight: '300'
h2b: 
  font-family: Roboto
  font-size: 24px
  font-weight: '700'
h3:
  font-family: Roboto
  font-size: 20px
h3b:
  font-family: Roboto
  font-size: 20px
  font-weight: '700'

c1:
  font-family: Roboto
  font-size: 14px
  font-weight: '300'
c1b:
  font-family: Roboto
  font-size: 16px
  font-weight: '500'

c1tb:
  font-family: Roboto
  font-size: 14px
  font-weight: '400'

c1s:
  font-family: Roboto
  font-size: 12px
  font-weight: '300'
  letter-spacing: 0.5px

c1sb:
  font-family: Roboto
  font-size: 12px
  font-weight: '600'
  letter-spacing: 0.5px

c2:
  font-family: Roboto
  font-size: 18px
  font-weight: '300'

c2b:
  font-family: Roboto
  font-size: 18px
  font-weight: '500'

404:
  font-family: Monoton
  font-size: 75px
